// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint

// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBL-8-bVOWZJB5wexGvypnrBgkFBRl9qOg',
//     appId: '1:821136037781:web:355dd6c3171d36d2a8889c',
//     messagingSenderId: '821136037781',
//     projectId: 'portfolio-d9f60',
//     authDomain: 'portfolio-d9f60.firebaseapp.com',
//     storageBucket: 'portfolio-d9f60.firebasestorage.app',
//     measurementId: 'G-PZS8S6FXXQ',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAvkNBIGMbbeh6SDhKIgRU7Luhvt3QHTbo',
//     appId: '1:821136037781:android:7a06691788108fa6a8889c',
//     messagingSenderId: '821136037781',
//     projectId: 'portfolio-d9f60',
//     storageBucket: 'portfolio-d9f60.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBEb0wpTqz56rTLUn6k16N87wAalonin3Q',
//     appId: '1:821136037781:ios:392bc575ac275ddea8889c',
//     messagingSenderId: '821136037781',
//     projectId: 'portfolio-d9f60',
//     storageBucket: 'portfolio-d9f60.firebasestorage.app',
//     iosBundleId: 'com.example.myPortifolio',
//   );
// }
